### ISSUE TITLE
Overlay Network - Docker Service veth is null

### ISSUE THREAD

**Issue by jgeorg02** [cslev/find_veth_docker#2]
Hello,

I am trying to find an easy way to find the veths for my docker containers, and your tool seems to be working perfectly for containers that use local networks, nevertheless for docker containers that use overlay networks I get the following output:

`Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
		null	null					my_docker_service.1.mguxaw0n8vckg907glzrpaeg4
`

**Comment by cslev** [comment]
hi, can you provide an example `docker-compose.yaml` file for me to reproduce your setting?

Thanks

**Comment by jgeorg02** [comment]
This is an example docker-compose.yaml that I deployed it to test it and didn't work:
`version: '3.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:latest
    restart: always
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager
          
  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - zookeeper
      - nimbus
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager

networks:
  storm_overlay_network:
    external: true`

**Comment by jgeorg02** [comment]
> hi, can you provide an example `docker-compose.yaml` file for me to reproduce your setting?
> 
> Thanks

This is an example docker-compose.yaml that I deployed it to test it and didn't work:
```
version: '3.3'
services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:latest
    restart: always
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager

  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager
          
  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - zookeeper
      - nimbus
    networks: 
      - storm_overlay_network
    deploy:
      placement:
        constraints:
          - node.role==manager

networks:
  storm_overlay_network:
    external: true
```
